cube.o: cube.cpp
	g++ -c cube.cpp

camera3d.o: camera3d.cpp
	g++ -c camera3d.cpp

matrix.o: matrix.cpp
	g++ -c matrix.cpp

point3D.o: point3D.cpp
	g++ -c point3D.cpp

globals.o: globals.cpp
	g++ -c globals.cpp
